// examples/example-pokemon-svelte/src/components/App.svelte
<script lang="ts">
  import { Client, setContextClient, cacheExchange, fetchExchange } from "@urql/svelte";
  import PokemonList from "./PokemonList.svelte";

  setContextClient(new Client({
    url: "https://trygql.formidable.dev/graphql/basic-pokedex",
    exchanges: [cacheExchange, fetchExchange],
  }));
</script>

<PokemonList />

// examples/example-pokemon-api/src/components/App.tsx
import { Client, Provider, cacheExchange, fetchExchange } from 'urql';

import { PokemonList } from './PokemonList';

const client = new Client({
  url: 'https://trygql.formidable.dev/graphql/basic-pokedex',
  exchanges: [cacheExchange, fetchExchange],
});

function App() {
  return (
    <Provider value={client}>
      <PokemonList />
    </Provider>
  );
}

export default App;
