// examples/example-pokemon-vue/src/components/App.vue
<script setup lang="ts">
import { Client, cacheExchange, fetchExchange, provideClient } from "@urql/vue";
import PokemonList from "./PokemonList.vue";

const client = new Client({
  url: "https://trygql.formidable.dev/graphql/basic-pokedex",
  exchanges: [cacheExchange, fetchExchange],
});

provideClient(client);
</script>
<template>
  <PokemonList />
</template>

// examples/example-pokemon-svelte/src/components/App.svelte
<script lang="ts">
  import { Client, setContextClient, cacheExchange, fetchExchange } from "@urql/svelte";
  import PokemonList from "./PokemonList.svelte";

  setContextClient(new Client({
    url: "https://trygql.formidable.dev/graphql/basic-pokedex",
    exchanges: [cacheExchange, fetchExchange],
  }));
</script>

<PokemonList />
