// examples/example-pokemon-svelte/src/components/PokemonTypes.svelte
<script context="module" lang="ts">
  import type { FragmentOf } from "../graphql";
  import { graphql, readFragment } from "../graphql";

  export const pokemonTypesFragment = graphql(`
    fragment PokemonTypes on Pokemon {
      types
    }
  `);
</script>

<script lang="ts">
  export let data: FragmentOf<typeof PokemonTypesFragment> | null;
  const pokemon = readFragment(pokemonTypesFragment, data);
</script>

{#if pokemon.types}
  <div>
    <h2>Types</h2>
    <ul>
      {#each pokemon.types as type}
        <li>{type}</li>
      {/each}
    </ul>
  </div>
{/if}

// examples/example-pokemon-vue/src/components/PokemonTypes.vue
<script lang="ts">
import { computed } from "vue";
import { FragmentOf, graphql, readFragment } from "../graphql";

export const pokemonTypesFragment = graphql(`
  fragment PokemonTypes on Pokemon {
    types
  }
`);
</script>
<script setup lang="ts">
const props = defineProps<{
  data: FragmentOf<typeof pokemonTypesFragment> | null;
}>();

const data = computed(() => readFragment(pokemonTypesFragment, props.data));
</script>
<template>
  <div>
    <h2>Types</h2>
    <ul>
      <li v-for="(type, i) in data?.types" :key="i">
        {{ type }}
      </li>
    </ul>
  </div>
</template>
