// examples/example-pokemon-svelte/src/components/PokemonItem.svelte
<script context="module" lang="ts">
  import type { FragmentOf } from "../graphql";
  import { graphql, readFragment } from "../graphql";
  import PokemonTypes, { pokemonTypesFragment } from "./PokemonTypes.svelte";

  export const PokemonItemFragment = graphql(
    `
      fragment PokemonItem on Pokemon {
        id
        name
        ...PokemonTypes
      }
    `,
    [pokemonTypesFragment]
  );
</script>

<script lang="ts">
  export let data: FragmentOf<typeof PokemonItemFragment> | null;
  const pokemon = readFragment(PokemonItemFragment, data);
</script>

<li v-if="pokemon">
  <p>{pokemon.name}</p>
  <PokemonTypes data={pokemon} />
</li>

// examples/example-pokemon-vue/src/components/PokemonItem.vue
<script lang="ts">
import { graphql } from "../graphql";
import PokemonTypes, { pokemonTypesFragment } from "./PokemonTypes.vue";

export const PokemonItemFragment = graphql(
  `
    fragment PokemonItem on Pokemon {
      id
      name
      ...PokemonTypes
    }
  `,
  [pokemonTypesFragment]
);
</script>
<script setup lang="ts">
import { FragmentOf, readFragment } from "../graphql";
import { ref, computed } from "vue";

const props = defineProps<{
  data: FragmentOf<typeof PokemonItemFragment> | null;
}>();

const pokemon = computed(() => readFragment(PokemonItemFragment, props.data));
</script>
<template>
  <li v-if="pokemon">
    <p>{{ pokemon.name }}</p>
    <PokemonTypes :data="pokemon" />
  </li>
</template>
